import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useForm } from "react-hook-form";
import Layout from "../components/Layout"
import { useRouter } from 'next/router'

type TData = {
    name?: string
}

const Login: NextPage = () => {
    const { register, handleSubmit } = useForm({ shouldUseNativeValidation: true });
    const router = useRouter()
    const onSubmit = (data: TData): void => {
        const { name } = data;
        window.localStorage.setItem('name', name || "");
        router.push("/")
    };
    return (
        <div className={styles.container}>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
                <div className={styles.grid}>
                    <form onSubmit={handleSubmit(onSubmit)}>
                        <input
                            {...register("name", { required: "Please enter your first name." })} // custom message
                        />
                        <input type="submit" />
                    </form>
                </div>
            </Layout>
        </div>
    )
}

export default Login
